AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: VPC to deploy the cluster into

  PublicSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet 1 to deploy the cluster into

  PrivateSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: Private subnet 1 to deploy the cluster into

  DBName:
    Type: String
    Description: The name of the database to create

  
Resources:
  DBCluster:
    Type: AWS::RDS::DBCluster
    DependsOn:
         - DBSubnetGroup
    Properties:
      Engine: aurora-mysql
      EngineVersion: '5.7'
      EngineMode: serverless
      DBClusterIdentifier: aurora-cluster
      DatabaseName: !Ref DBName
      MasterUsername: user
      MasterUserPassword: password
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DBSecurityGroup
      ScalingConfiguration:
        AutoPause: 'true'
        SecondsUntilAutoPause: 300
        MaxCapacity: 2
        MinCapacity: 1
      Tags:
        - Key: Name
          Value: aurora-cluster

  DBSubnetGroup:
     Type: AWS::RDS::DBSubnetGroup
     Properties:
      DBSubnetGroupDescription: Subnets available for the Aurora database cluster
      SubnetIds:
        - !Ref PrivateSubnet
        - !Ref DBSubnet1
        

  DBSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: "10.192.13.0/24"
      Tags:
        - Key: Name
          Value: DBSubnet1

  # DBSubnet2:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     VpcId: !Ref VPC
  #     AvailabilityZone: !Select [1, !GetAZs '']
  #     CidrBlock: "10.192.14.0/24"
  #     Tags:
  #       - Key: Name
  #         Value: DBSubnet2
  
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Aurora cluster
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: 0.0.0.0/0

 
Outputs:
   DBEndpoint:
    Description: The connection endpoint of your database.
    Value: !Join 
      - ''
      - - !GetAtt DBCluster.Endpoint.Address
        - ':'
        - !GetAtt DBCluster.Endpoint.Port
        - /
        - !Ref DBName